- pragma:
    implied-branches:
      - stable/queens
      - stable/luminous

- job:
    name: puppet-openstack-base
    pre-run: playbooks/prepare-node-common.yaml
    vars:
      use_puppetlabs: false

- job:
    name: puppet-openstack-integration-base
    parent: puppet-openstack-base
    required-projects:
      - name: openstack/openstack
      - name: openstack/puppet-aodh
        override-checkout: stable/queens
      - name: openstack/puppet-barbican
        override-checkout: stable/queens
      - name: openstack/puppet-ceilometer
        override-checkout: stable/queens
      - name: openstack/puppet-ceph
        override-checkout: stable/luminous
      - name: openstack/puppet-cinder
        override-checkout: stable/queens
      - name: openstack/puppet-cloudkitty
        override-checkout: stable/queens
      - name: openstack/puppet-designate
        override-checkout: stable/queens
      - name: openstack/puppet-ec2api
        override-checkout: stable/queens
      - name: openstack/puppet-glance
        override-checkout: stable/queens
      - name: openstack/puppet-gnocchi
        override-checkout: stable/queens
      - name: openstack/puppet-heat
        override-checkout: stable/queens
      - name: openstack/puppet-horizon
        override-checkout: stable/queens
      - name: openstack/puppet-ironic
        override-checkout: stable/queens
      - name: openstack/puppet-keystone
        override-checkout: stable/queens
      - name: openstack/puppet-manila
        override-checkout: stable/queens
      - name: openstack/puppet-mistral
        override-checkout: stable/queens
      - name: openstack/puppet-monasca
        override-checkout: stable/queens
      - name: x/puppet-modulesync-configs
        override-checkout: stable/queens
      - name: openstack/puppet-murano
        override-checkout: stable/queens
      - name: openstack/puppet-neutron
        override-checkout: stable/queens
      - name: openstack/puppet-nova
        override-checkout: stable/queens
      - name: openstack/puppet-octavia
        override-checkout: stable/queens
      - name: openstack/puppet-openstack-cookiecutter
        override-checkout: stable/queens
      - name: openstack/puppet-openstack-integration
        override-checkout: stable/queens
      - name: openstack/puppet-openstack_extras
        override-checkout: stable/queens
      - name: openstack/puppet-openstacklib
        override-checkout: stable/queens
      - name: openstack/puppet-oslo
        override-checkout: stable/queens
      - name: openstack/puppet-ovn
        override-checkout: stable/queens
      - name: openstack/puppet-panko
        override-checkout: stable/queens
      - name: openstack/puppet-qdr
        override-checkout: stable/queens
      - name: openstack/puppet-sahara
        override-checkout: stable/queens
      - name: openstack/puppet-swift
        override-checkout: stable/queens
      - name: openstack/puppet-tacker
        override-checkout: stable/queens
      - name: openstack/puppet-tempest
        override-checkout: stable/queens
      - name: openstack/puppet-trove
        override-checkout: stable/queens
      - name: openstack/puppet-vswitch
        override-checkout: stable/queens
      - name: openstack/puppet-vitrage
        override-checkout: stable/queens
      - name: openstack/puppet-watcher
        override-checkout: stable/queens
      - name: openstack/puppet-zaqar
        override-checkout: stable/queens
      - name: openstack/tempest
        override-checkout: 22.1.0
      - name: openstack/tempest-horizon
        override-checkout: 0.2.0

- job:
    name: puppet-openstack-integration-run-base
    parent: puppet-openstack-integration-base
    pre-run: playbooks/prepare-node-integration.yaml
    run: playbooks/run-integration-tests.yaml
    post-run: playbooks/upload-logs.yaml
    timeout: 5400
    irrelevant-files:
      - ^.*\.md$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^spec/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitignore$
    roles:
      - zuul: zuul/zuul-jobs
    # NOTE(tobasco): The ceph variable must be provided with a default here
    # or zuul will complain when it tries to render the run-integration-tests template.
    vars:
      ceph: luminous

- job:
    name: puppet-openstack-integration-4
    parent: puppet-openstack-integration-run-base
    vars:
      puppet: 4

- job:
    name: puppet-openstack-integration-4-scenario001
    parent: puppet-openstack-integration-4
    vars:
      scenario: scenario001
      ceph: luminous

- job:
    name: puppet-openstack-integration-4-scenario001-tempest-ubuntu-xenial-luminous
    parent: puppet-openstack-integration-4-scenario001
    nodeset: ubuntu-xenial
    voting: false

- job:
    name: puppet-openstack-integration-4-scenario001-tempest-centos-7-luminous
    parent: puppet-openstack-integration-4-scenario001
    nodeset: centos-7

- job:
    name: puppet-openstack-integration-4-scenario002
    parent: puppet-openstack-integration-4
    vars:
      scenario: scenario002

- job:
    name: puppet-openstack-integration-4-scenario002-tempest-ubuntu-xenial
    parent: puppet-openstack-integration-4-scenario002
    nodeset: ubuntu-xenial
    voting: false

- job:
    name: puppet-openstack-integration-4-scenario002-tempest-centos-7
    parent: puppet-openstack-integration-4-scenario002
    nodeset: centos-7

- job:
    name: puppet-openstack-integration-4-scenario003
    parent: puppet-openstack-integration-4
    vars:
      scenario: scenario003

- job:
    name: puppet-openstack-integration-4-scenario003-tempest-ubuntu-xenial
    parent: puppet-openstack-integration-4-scenario003
    nodeset: ubuntu-xenial
    voting: false

- job:
    name: puppet-openstack-integration-4-scenario003-tempest-centos-7
    parent: puppet-openstack-integration-4-scenario003
    nodeset: centos-7

- job:
    name: puppet-openstack-integration-4-scenario004
    parent: puppet-openstack-integration-4
    vars:
      scenario: scenario004
      ceph: luminous

- job:
    name: puppet-openstack-integration-4-scenario004-tempest-ubuntu-xenial-luminous
    parent: puppet-openstack-integration-4-scenario004
    nodeset: ubuntu-xenial
    voting: false

- job:
    name: puppet-openstack-integration-4-scenario004-tempest-centos-7-luminous
    parent: puppet-openstack-integration-4-scenario004
    nodeset: centos-7

- job:
    name: puppet-openstack-integration-5
    parent: puppet-openstack-integration-run-base
    voting: false
    vars:
      puppet: 5

- job:
    name: puppet-openstack-integration-5-scenario001
    parent: puppet-openstack-integration-5
    vars:
      scenario: scenario001
      ceph: luminous

- job:
    name: puppet-openstack-integration-5-scenario001-tempest-ubuntu-xenial-luminous
    parent: puppet-openstack-integration-5-scenario001
    nodeset: ubuntu-xenial

- job:
    name: puppet-openstack-integration-5-scenario001-tempest-centos-7-luminous
    parent: puppet-openstack-integration-5-scenario001
    nodeset: centos-7

- job:
    name: puppet-openstack-integration-5-scenario002
    parent: puppet-openstack-integration-5
    vars:
      scenario: scenario002

- job:
    name: puppet-openstack-integration-5-scenario002-tempest-ubuntu-xenial
    parent: puppet-openstack-integration-5-scenario002
    nodeset: ubuntu-xenial

- job:
    name: puppet-openstack-integration-5-scenario002-tempest-centos-7
    parent: puppet-openstack-integration-5-scenario002
    nodeset: centos-7

- job:
    name: puppet-openstack-integration-5-scenario003
    parent: puppet-openstack-integration-5
    vars:
      scenario: scenario003

- job:
    name: puppet-openstack-integration-5-scenario003-tempest-ubuntu-xenial
    parent: puppet-openstack-integration-5-scenario003
    nodeset: ubuntu-xenial

- job:
    name: puppet-openstack-integration-5-scenario003-tempest-centos-7
    parent: puppet-openstack-integration-5-scenario003
    nodeset: centos-7

- job:
    name: puppet-openstack-integration-5-scenario004
    parent: puppet-openstack-integration-5
    vars:
      scenario: scenario004
      ceph: luminous

- job:
    name: puppet-openstack-integration-5-scenario004-tempest-ubuntu-xenial-luminous
    parent: puppet-openstack-integration-5-scenario004
    nodeset: ubuntu-xenial

- job:
    name: puppet-openstack-integration-5-scenario004-tempest-centos-7-luminous
    parent: puppet-openstack-integration-5-scenario004
    nodeset: centos-7

- project-template:
    name: puppet-openstack-integration-jobs-all
    check:
      jobs:
        - puppet-openstack-integration-4-scenario001-tempest-centos-7-luminous
        - puppet-openstack-integration-4-scenario002-tempest-centos-7
        - puppet-openstack-integration-4-scenario003-tempest-centos-7
        - puppet-openstack-integration-4-scenario004-tempest-centos-7-luminous
        - puppet-openstack-integration-4-scenario001-tempest-ubuntu-xenial-luminous
        - puppet-openstack-integration-4-scenario002-tempest-ubuntu-xenial
        - puppet-openstack-integration-4-scenario003-tempest-ubuntu-xenial
        - puppet-openstack-integration-4-scenario004-tempest-ubuntu-xenial-luminous
    gate:
      jobs:
        - puppet-openstack-integration-4-scenario001-tempest-centos-7-luminous
        - puppet-openstack-integration-4-scenario002-tempest-centos-7
        - puppet-openstack-integration-4-scenario003-tempest-centos-7
        - puppet-openstack-integration-4-scenario004-tempest-centos-7-luminous
    experimental:
      jobs:
        - puppet-openstack-integration-5-scenario001-tempest-centos-7-luminous
        - puppet-openstack-integration-5-scenario002-tempest-centos-7
        - puppet-openstack-integration-5-scenario003-tempest-centos-7
        - puppet-openstack-integration-5-scenario004-tempest-centos-7-luminous
        - puppet-openstack-integration-5-scenario001-tempest-ubuntu-xenial-luminous
        - puppet-openstack-integration-5-scenario002-tempest-ubuntu-xenial
        - puppet-openstack-integration-5-scenario003-tempest-ubuntu-xenial
        - puppet-openstack-integration-5-scenario004-tempest-ubuntu-xenial-luminous

- project-template:
    name: puppet-openstack-integration-jobs-scenario001
    check:
      jobs:
        - puppet-openstack-integration-4-scenario001-tempest-ubuntu-xenial-luminous
        - puppet-openstack-integration-4-scenario001-tempest-centos-7-luminous
    gate:
      jobs:
        - puppet-openstack-integration-4-scenario001-tempest-ubuntu-xenial-luminous
    experimental:
      jobs:
        - puppet-openstack-integration-5-scenario001-tempest-ubuntu-xenial-luminous
        - puppet-openstack-integration-5-scenario001-tempest-centos-7-luminous

- project-template:
    name: puppet-openstack-integration-jobs-scenario002
    check:
      jobs:
        - puppet-openstack-integration-4-scenario002-tempest-ubuntu-xenial
        - puppet-openstack-integration-4-scenario002-tempest-centos-7
    gate:
      jobs:
        - puppet-openstack-integration-4-scenario002-tempest-centos-7
    experimental:
      jobs:
        - puppet-openstack-integration-5-scenario002-tempest-ubuntu-xenial
        - puppet-openstack-integration-5-scenario002-tempest-centos-7

- project-template:
    name: puppet-openstack-integration-jobs-scenario003
    check:
      jobs:
        - puppet-openstack-integration-4-scenario003-tempest-ubuntu-xenial
        - puppet-openstack-integration-4-scenario003-tempest-centos-7
    gate:
      jobs:
        - puppet-openstack-integration-4-scenario003-tempest-centos-7
    experimental:
      jobs:
        - puppet-openstack-integration-5-scenario003-tempest-ubuntu-xenial
        - puppet-openstack-integration-5-scenario003-tempest-centos-7

- project-template:
    name: puppet-openstack-integration-jobs-scenario004
    check:
      jobs:
        - puppet-openstack-integration-4-scenario004-tempest-ubuntu-xenial-luminous
        - puppet-openstack-integration-4-scenario004-tempest-centos-7-luminous
    gate:
      jobs:
        - puppet-openstack-integration-4-scenario004-tempest-ubuntu-xenial-luminous
    experimental:
      jobs:
        - puppet-openstack-integration-5-scenario004-tempest-ubuntu-xenial-luminous
        - puppet-openstack-integration-5-scenario004-tempest-centos-7-luminous

- job:
    name: puppet-openstack-module-base
    parent: puppet-openstack-base
    pre-run: playbooks/prepare-node-unit.yaml

- job:
    name: puppet-openstack-lint
    parent: puppet-openstack-module-base
    run: playbooks/run-lint-tests.yaml
    irrelevant-files:
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$

- job:
    name: puppet-openstack-syntax
    parent: puppet-openstack-module-base
    run: playbooks/run-syntax-tests.yaml
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$

- job:
    name: puppet-openstack-syntax-4
    parent: puppet-openstack-syntax
    vars:
      puppet: 4

- job:
    name: puppet-openstack-unit-base
    parent: puppet-openstack-integration-base
    run: playbooks/run-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^spec/acceptance/.*$

- job:
    name: puppet-openstack-unit-4.8-centos-7
    parent: puppet-openstack-unit-base
    nodeset: centos-7
    vars:
      puppet_gem_version: 4.8

- job:
    name: puppet-openstack-unit-5.5-centos-7
    parent: puppet-openstack-unit-base
    nodeset: centos-7
    vars:
      puppet_gem_version: 5.5

- project-template:
    name: puppet-openstack-module-unit-jobs
    check:
      jobs:
        - puppet-openstack-unit-4.8-centos-7
        - puppet-openstack-unit-5.5-centos-7
    gate:
      jobs:
        - puppet-openstack-unit-4.8-centos-7
        - puppet-openstack-unit-5.5-centos-7

- project-template:
    name: puppet-openstack-check-jobs
    check:
      jobs:
        - puppet-openstack-lint
        - puppet-openstack-syntax-4
    gate:
      jobs:
        - puppet-openstack-lint
        - puppet-openstack-syntax-4

- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-integration-jobs-all

- job:
    name: puppet-openstack-beaker-run-base
    parent: puppet-openstack-integration-base
    pre-run: playbooks/prepare-node-beaker.yaml
    post-run: playbooks/upload-logs.yaml
    run: playbooks/run-beaker-tests.yaml
    timeout: 5400
    irrelevant-files:
      - ^.*\.md$
      - ^spec/unit/.*$
      - ^spec/classes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^metadata.json$

- job:
    name: puppet-openstack-beaker-centos-7
    parent: puppet-openstack-beaker-run-base
    nodeset: centos-7
    vars:
      nodepool_type: centos7

- job:
    name: puppet-openstack-beaker-xenial
    parent: puppet-openstack-beaker-run-base
    nodeset: ubuntu-xenial
    vars:
      nodepool_type: xenial
    voting: false

- project-template:
    name: puppet-openstack-beaker-jobs
    check:
      jobs:
        - puppet-openstack-beaker-centos-7
        - puppet-openstack-beaker-xenial
    gate:
      jobs:
        - puppet-openstack-beaker-centos-7
        - puppet-openstack-beaker-xenial

- job:
    name: puppet-openstack-libraries-puppet-beaker-rspec-centos-7
    parent: puppet-openstack-integration-base
    pre-run: playbooks/prepare-node-beaker.yaml
    post-run: playbooks/upload-logs.yaml
    run: playbooks/run-libraries-beaker-tests.yaml
    timeout: 3600
    nodeset: centos-7
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^test-requirements.txt$

- job:
    name: puppet-openstack-libraries-puppet-lint-centos-7
    parent: puppet-openstack-integration-base
    run: playbooks/run-libraries-lint-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    nodeset: centos-7

- job:
    name: puppet-openstack-libraries-puppet-syntax
    parent: puppet-openstack-integration-base
    run: playbooks/run-libraries-syntax-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^test-requirements.txt$

- job:
    name: puppet-openstack-libraries-puppet-syntax-4-centos-7
    parent: puppet-openstack-libraries-puppet-syntax
    nodeset: centos-7
    vars:
      puppet: 4

- job:
    name: puppet-openstack-libraries-puppet-unit-centos-7
    parent: puppet-openstack-integration-base
    run: playbooks/run-libraries-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    nodeset: centos-7
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^test-requirements.txt$

- project-template:
    name: puppet-openstack-library-jobs
    check:
      jobs:
        - puppet-openstack-libraries-puppet-lint-centos-7
        - puppet-openstack-libraries-puppet-syntax-4-centos-7
        - puppet-openstack-libraries-puppet-unit-centos-7
        - puppet-openstack-libraries-puppet-beaker-rspec-centos-7
    gate:
      jobs:
        - puppet-openstack-libraries-puppet-lint-centos-7
        - puppet-openstack-libraries-puppet-syntax-4-centos-7
        - puppet-openstack-libraries-puppet-unit-centos-7
        - puppet-openstack-libraries-puppet-beaker-rspec-centos-7
