- job:
    name: puppet-openstack-integration-base
    abstract: true
    parent: puppet-openstack-base
    required-projects:
      - openstack/openstack
      - openstack/puppet-aodh
      - openstack/puppet-barbican
      - openstack/puppet-ceilometer
      - openstack/puppet-ceph
      - openstack/puppet-cinder
      - openstack/puppet-cloudkitty
      - openstack/puppet-designate
      - openstack/puppet-ec2api
      - openstack/puppet-glance
      - openstack/puppet-gnocchi
      - openstack/puppet-heat
      - openstack/puppet-horizon
      - openstack/puppet-ironic
      - openstack/puppet-keystone
      - openstack/puppet-magnum
      - openstack/puppet-manila
      - openstack/puppet-mistral
      - openstack/puppet-monasca
      - x/puppet-modulesync-configs
      - openstack/puppet-murano
      - openstack/puppet-neutron
      - openstack/puppet-nova
      - openstack/puppet-octavia
      - openstack/puppet-openstack-cookiecutter
      - openstack/puppet-openstack-integration
      - openstack/puppet-openstack_extras
      - openstack/puppet-openstacklib
      - openstack/puppet-oslo
      - openstack/puppet-ovn
      - openstack/puppet-panko
      - openstack/puppet-placement
      - openstack/puppet-qdr
      - openstack/puppet-sahara
      - openstack/puppet-swift
      - openstack/puppet-tacker
      - openstack/puppet-tempest
      - openstack/puppet-trove
      - openstack/puppet-vswitch
      - openstack/puppet-vitrage
      - openstack/puppet-watcher
      - openstack/puppet-zaqar
      - openstack/tempest
      - openstack/tempest-horizon

- job:
    name: puppet-openstack-integration-run-base
    parent: puppet-openstack-integration-base
    abstract: true
    pre-run: playbooks/prepare-node-integration.yaml
    run: playbooks/run-integration-tests.yaml
    post-run: playbooks/upload-logs.yaml
    timeout: 7200
    irrelevant-files:
      - ^.*\.md$
      - ^doc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^spec/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
    roles:
      - zuul: zuul/zuul-jobs
    # NOTE(tobasco): The ceph variable must be provided with a default here
    # or zuul will complain when it tries to render the run-integration-tests template.
    vars:
      ceph: luminous

- job:
    name: puppet-openstack-base
    pre-run: playbooks/prepare-node-common.yaml
    abstract: true
    nodeset: ubuntu-bionic
    vars:
      use_puppetlabs: false

- job:
    name: puppet-openstack-module-base
    parent: puppet-openstack-base
    pre-run: playbooks/prepare-node-unit.yaml


- job:
    name: puppet-openstack-syntax-base
    parent: puppet-openstack-module-base
    run: playbooks/run-syntax-tests.yaml
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$

- job:
    name: puppet-openstack-unit-base
    parent: puppet-openstack-integration-base
    run: playbooks/run-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^spec/acceptance/.*$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
    # TODO(tobias-urdin): Remove when we use rspec-puppet 2.7.1
    vars:
      rspec_puppet_version: '~> 2.3.0'

- job:
    name: puppet-openstack-libraries-puppet-unit-base
    parent: puppet-openstack-integration-base
    run: playbooks/run-libraries-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
    # TODO(tobias-urdin): Remove when we use rspec-puppet 2.7.1
    vars:
      rspec_puppet_version: '~> 2.3.0'

- job:
    name: puppet-openstack-beaker-run-base
    parent: puppet-openstack-integration-base
    abstract: true
    pre-run: playbooks/prepare-node-beaker.yaml
    post-run: playbooks/upload-logs.yaml
    run: playbooks/run-beaker-tests.yaml
    timeout: 5400
    irrelevant-files:
      - ^.*\.md$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^spec/unit/.*$
      - ^spec/classes/.*$
      - ^spec/defines/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^metadata.json$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$

- job:
    name: puppet-openstack-beaker-centos-8
    parent: puppet-openstack-beaker-run-base
    nodeset: centos-8
    voting: false
    vars:
      nodepool_type: centos8
      puppet_gem_version: 5.5

- job:
    name: puppet-openstack-beaker-ubuntu-bionic
    parent: puppet-openstack-beaker-run-base
    nodeset: ubuntu-bionic
    voting: false
    vars:
      nodepool_type: bionic
      puppet_gem_version: latest
