---
- job:
    name: puppet-openstack-integration-base
    abstract: true
    parent: puppet-openstack-base
    required-projects:
      - name: openstack/openstack
        override-checkout: stable/yoga
      - name: openstack/puppet-aodh
        override-checkout: stable/yoga
      - name: openstack/puppet-barbican
        override-checkout: stable/yoga
      - name: openstack/puppet-ceilometer
        override-checkout: stable/yoga
      - openstack/puppet-ceph
      - name: openstack/puppet-cinder
        override-checkout: stable/yoga
      - name: openstack/puppet-cloudkitty
        override-checkout: stable/yoga
      - name: openstack/puppet-designate
        override-checkout: stable/yoga
      - name: openstack/puppet-ec2api
        override-checkout: stable/yoga
      - name: openstack/puppet-glance
        override-checkout: stable/yoga
      - name: openstack/puppet-gnocchi
        override-checkout: stable/yoga
      - name: openstack/puppet-heat
        override-checkout: stable/yoga
      - name: openstack/puppet-horizon
        override-checkout: stable/yoga
      - name: openstack/puppet-ironic
        override-checkout: stable/yoga
      - name: openstack/puppet-keystone
        override-checkout: stable/yoga
      - name: openstack/puppet-magnum
        override-checkout: stable/yoga
      - name: openstack/puppet-manila
        override-checkout: stable/yoga
      - name: openstack/puppet-mistral
        override-checkout: stable/yoga
      - x/puppet-modulesync-configs
      - name: openstack/puppet-murano
        override-checkout: stable/yoga
      - name: openstack/puppet-neutron
        override-checkout: stable/yoga
      - name: openstack/puppet-nova
        override-checkout: stable/yoga
      - name: openstack/puppet-octavia
        override-checkout: stable/yoga
      - openstack/puppet-openstack-cookiecutter
      - name: openstack/puppet-openstack-integration
        override-checkout: stable/yoga
      - name: openstack/puppet-openstack_extras
        override-checkout: stable/yoga
      - name: openstack/puppet-openstack_spec_helper
        override-checkout: stable/yoga
      - name: openstack/puppet-openstacklib
        override-checkout: stable/yoga
      - name: openstack/puppet-oslo
        override-checkout: stable/yoga
      - name: openstack/puppet-ovn
        override-checkout: stable/yoga
      - name: openstack/puppet-placement
        override-checkout: stable/yoga
      - name: openstack/puppet-qdr
        override-checkout: stable/yoga
      - name: openstack/puppet-sahara
        override-checkout: stable/yoga
      - name: openstack/puppet-swift
        override-checkout: stable/yoga
      - name: openstack/puppet-tempest
        override-checkout: stable/yoga
      - name: openstack/puppet-trove
        override-checkout: stable/yoga
      - name: openstack/puppet-vswitch
        override-checkout: stable/yoga
      - name: openstack/puppet-vitrage
        override-checkout: stable/yoga
      - name: openstack/puppet-watcher
        override-checkout: stable/yoga
      - name: openstack/puppet-zaqar
        override-checkout: stable/yoga
      - openstack/tempest
      - openstack/neutron-tempest-plugin

- job:
    name: puppet-openstack-integration-run-base
    parent: puppet-openstack-integration-base
    abstract: true
    pre-run: playbooks/prepare-node-integration.yaml
    run: playbooks/run-integration-tests.yaml
    post-run:
      - playbooks/copy-logs.yaml
      - playbooks/upload-logs.yaml
    timeout: 7200
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^examples/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^spec/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitreview$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
      - ^tox.ini$
    roles:
      - zuul: zuul/zuul-jobs
    vars:
      ceph: pacific

- job:
    name: puppet-openstack-base
    pre-run: playbooks/prepare-node-common.yaml
    abstract: true
    nodeset: ubuntu-focal
    vars:
      puppet: 6
      use_puppetlabs: false

- job:
    name: puppet-openstack-module-base
    parent: puppet-openstack-base
    pre-run: playbooks/prepare-node-unit.yaml


- job:
    name: puppet-openstack-syntax-base
    parent: puppet-openstack-module-base
    run: playbooks/run-syntax-tests.yaml
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitreview$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
      - ^tox.ini$

- job:
    name: puppet-openstack-unit-base
    parent: puppet-openstack-integration-base
    run: playbooks/run-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^examples/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^spec/acceptance/.*$
      - ^LICENSE$
      - ^.gitreview$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
      - ^tox.ini$
    vars:
      rspec_puppet_version: '~> 2.8.0'

- job:
    name: puppet-openstack-libraries-puppet-unit-base
    parent: puppet-openstack-integration-base
    run: playbooks/run-libraries-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^examples/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^spec/acceptance/.*$
      - ^LICENSE$
      - ^.gitreview$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
      - ^tox.ini$
    vars:
      rspec_puppet_version: '~> 2.8.0'
