- pragma:
    implied-branches:
      - stable/train

- job:
    name: puppet-openstack-integration-base
    abstract: true
    parent: puppet-openstack-base
    required-projects:
      - name: openstack/openstack
      - name: openstack/puppet-aodh
        override-checkout: stable/train
      - name: openstack/puppet-barbican
        override-checkout: stable/train
      - name: openstack/puppet-ceilometer
        override-checkout: stable/train
      - name: openstack/puppet-ceph
        override-checkout: master
      - name: openstack/puppet-cinder
        override-checkout: stable/train
      - name: openstack/puppet-cloudkitty
        override-checkout: stable/train
      - name: openstack/puppet-designate
        override-checkout: stable/train
      - name: openstack/puppet-ec2api
        override-checkout: stable/train
      - name: openstack/puppet-glance
        override-checkout: stable/train
      - name: openstack/puppet-gnocchi
        override-checkout: stable/train
      - name: openstack/puppet-heat
        override-checkout: stable/train
      - name: openstack/puppet-horizon
        override-checkout: stable/train
      - name: openstack/puppet-ironic
        override-checkout: stable/train
      - name: openstack/puppet-keystone
        override-checkout: stable/train
      - name: openstack/puppet-manila
        override-checkout: stable/train
      - name: openstack/puppet-mistral
        override-checkout: stable/train
      - name: openstack/puppet-monasca
        override-checkout: stable/train
      - name: x/puppet-modulesync-configs
      - name: openstack/puppet-murano
        override-checkout: stable/train
      - name: openstack/puppet-neutron
        override-checkout: stable/train
      - name: openstack/puppet-nova
        override-checkout: stable/train
      - name: openstack/puppet-octavia
        override-checkout: stable/train
      - name: openstack/puppet-openstack-cookiecutter
      - name: openstack/puppet-openstack-integration
        override-checkout: stable/train
      - name: openstack/puppet-openstack_extras
        override-checkout: stable/train
      - name: openstack/puppet-openstacklib
        override-checkout: stable/train
      - name: openstack/puppet-oslo
        override-checkout: stable/train
      - name: openstack/puppet-ovn
        override-checkout: stable/train
      - name: openstack/puppet-panko
        override-checkout: stable/train
      - name: openstack/puppet-placement
        override-checkout: stable/train
      - name: openstack/puppet-qdr
        override-checkout: stable/train
      - name: openstack/puppet-sahara
        override-checkout: stable/train
      - name: openstack/puppet-swift
        override-checkout: stable/train
      - name: openstack/puppet-tacker
        override-checkout: stable/train
      - name: openstack/puppet-tempest
        override-checkout: stable/train
      - name: openstack/puppet-trove
        override-checkout: stable/train
      - name: openstack/puppet-vswitch
        override-checkout: stable/train
      - name: openstack/puppet-vitrage
        override-checkout: stable/train
      - name: openstack/puppet-watcher
        override-checkout: stable/train
      - name: openstack/puppet-zaqar
        override-checkout: stable/train
      - name: openstack/tempest
        override-checkout: 23.0.0

- job:
    name: puppet-openstack-integration-run-base
    parent: puppet-openstack-integration-base
    abstract: true
    pre-run: playbooks/prepare-node-integration.yaml
    run: playbooks/run-integration-tests.yaml
    post-run: playbooks/upload-logs.yaml
    timeout: 7200
    irrelevant-files:
      - ^.*\.md$
      - ^doc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^spec/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
    roles:
      - zuul: zuul/zuul-jobs
    # NOTE(tobasco): The ceph variable must be provided with a default here
    # or zuul will complain when it tries to render the run-integration-tests template.
    vars:
      ceph: luminous

- job:
    name: puppet-openstack-base
    pre-run: playbooks/prepare-node-common.yaml
    abstract: true
    nodeset: ubuntu-bionic
    vars:
      use_puppetlabs: false

- job:
    name: puppet-openstack-module-base
    parent: puppet-openstack-base
    pre-run: playbooks/prepare-node-unit.yaml


- job:
    name: puppet-openstack-syntax-base
    parent: puppet-openstack-module-base
    run: playbooks/run-syntax-tests.yaml
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$

- job:
    name: puppet-openstack-unit-base
    parent: puppet-openstack-integration-base
    run: playbooks/run-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^spec/acceptance/.*$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
    # TODO(tobias-urdin): Remove when we use rspec-puppet 2.7.1
    vars:
      rspec_puppet_version: '~> 2.3.0'

- job:
    name: puppet-openstack-libraries-puppet-unit-base
    parent: puppet-openstack-integration-base
    run: playbooks/run-libraries-unit-tests.yaml
    pre-run: playbooks/prepare-node-unit.yaml
    timeout: 3600
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^test-requirements.txt$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$
    # TODO(tobias-urdin): Remove when we use rspec-puppet 2.7.1
    vars:
      rspec_puppet_version: '~> 2.3.0'

- job:
    name: puppet-openstack-beaker-run-base
    parent: puppet-openstack-integration-base
    abstract: true
    pre-run: playbooks/prepare-node-beaker.yaml
    post-run: playbooks/upload-logs.yaml
    run: playbooks/run-beaker-tests.yaml
    timeout: 5400
    irrelevant-files:
      - ^.*\.md$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^spec/unit/.*$
      - ^spec/classes/.*$
      - ^spec/defines/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^metadata.json$
      - ^LICENSE$
      - ^.gitignore$
      - ^setup.cfg$
      - ^setup.py$

- job:
    name: puppet-openstack-beaker-centos-7
    parent: puppet-openstack-beaker-run-base
    nodeset: centos-7
    vars:
      nodepool_type: centos7
      puppet_gem_version: 5.5

- job:
    name: puppet-openstack-beaker-ubuntu-bionic
    parent: puppet-openstack-beaker-run-base
    nodeset: ubuntu-bionic
    voting: false
    vars:
      nodepool_type: bionic
      puppet_gem_version: latest
