- hosts: all
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          ZUUL_BRANCH_REAL=${ZUUL_BRANCH:-master}
          # Workaround for puppet-ceph, where we need to checkout
          # puppet-openstack-integration from stable/pike when working on
          # stable/jewel.
          # Ceph Jewel works with Newton to Pike
          if [[ "$ZUUL_BRANCH" == "stable/jewel" ]]; then
              ZUUL_BRANCH_REAL='stable/pike'
          fi
          if [ -d /home/zuul/src/opendev.org/openstack/puppet-openstack-integration ]; then
              [ ! -d puppet-openstack-integration ] && mkdir puppet-openstack-integration
              cp -dR /home/zuul/src/opendev.org/openstack/puppet-openstack-integration/. puppet-openstack-integration
          else
              git clone -b $ZUUL_BRANCH_REAL https://opendev.org/openstack/puppet-openstack-integration puppet-openstack-integration
          fi
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - include_role:
        name: bindep
      vars:
        bindep_dir: "src/opendev.org/openstack/puppet-openstack-integration"

    - name: Create folder for gems
      file:
        path: "{{ ansible_user_dir }}/workspace/puppet-openstack-integration/.bundled_gems"
        state: directory

    - name: Install bundler
      shell:
        cmd: |
          ruby <<EOF
          cmd = 'gem install bundler --no-document --verbose --no-user-install'
          cmd += ' -v 2.2.11'
          system(cmd)
          EOF
      environment:
        GEM_HOME: "{{ ansible_user_dir }}/workspace/puppet-openstack-integration/.bundled_gems"

    - name: Prepare swap
      shell:
        cmd: |
          dd if=/dev/zero of=/tmp/swapfile bs=1GiB count=4 && \
          chmod 0600 /tmp/swapfile && \
          mkswap /tmp/swapfile && \
          swapon /tmp/swapfile
      become: yes
