- hosts: all
  tasks:
    - name: Run Litmus
      shell:
        cmd: |
          set -e
          function trap_exit_sig() {
            {{ ansible_user_dir }}/workspace/puppet-openstack-integration/copy_logs.sh

            # NOTE(tobias-urdin): Litmus does not execute spec_clean rake task after a run.
            $GEM_BIN_DIR/bundle exec rake spec_clean
          }
          trap trap_exit_sig EXIT
          export CEPH_VERSION={{ ceph }}
          if [ "{{ puppet_gem_version }}" != "latest" ]; then
            export PUPPET_GEM_VERSION='~> {{ puppet_gem_version }}'
          fi
          mkdir .bundled_gems
          export GEM_HOME=`pwd`/.bundled_gems
          export GEM_BIN_DIR=$GEM_HOME/bin
          gem install bundler --no-document --verbose --no-user-install --bindir=${GEM_BIN_DIR}
          $GEM_BIN_DIR/bundle config set --local without system_tests
          $GEM_BIN_DIR/bundle install --retry 3
          export RSPEC_DEBUG=true
          $GEM_BIN_DIR/bundle exec rake litmus:acceptance:localhost
        chdir: '{{ ansible_user_dir }}/workspace'
        executable: /bin/bash
      become: yes
      environment: '{{ zuul | zuul_legacy_vars }}'
